name: Updates documentation
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: make update-docs
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update docs
